global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'identity-service'
    static_configs:
      - targets: ['identity-service:3001']

  - job_name: 'student-service'
    static_configs:
      - targets: ['student-service:3002']

  - job_name: 'teacher-service'
    static_configs:
      - targets: ['teacher-service:3003']

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:3004']

  - job_name: 'webhook-service'
    static_configs:
      - targets: ['webhook-service:3005']

  - job_name: 'ceo-api'
    static_configs:
      - targets: ['ceo-api:3006']
